// Auto-generated by train_scoring_weights.py — não editar manualmente

/** Árvore de decisão compacta exportada do sklearn GBM */
export interface GBMTree {
  /** children_left  */ cl: number[]
  /** children_right */ cr: number[]
  /** feature index  */ fi: number[]
  /** threshold      */ th: number[]
  /** leaf value     */ va: number[]
}

/** Modelo GBM (Gradient Boosting Machine) */
export interface GBMWeights {
  type: 'gbm'
  /** Previsão inicial (média dos targets de treino) */
  initPrediction: number
  learningRate: number
  /** Nomes das features na mesma ordem usada em computeScore.ts */
  featureNames: string[]
  trees: GBMTree[]
}

/** Modelo Ridge linear (backward-compat com arquivos antigos sem `type`) */
export interface LinearWeights {
  type?: 'linear'
  bias: number
  weights: Record<string, number>
}

export type ScoringWeights = LinearWeights | GBMWeights
